[package]
name = "ngx-rust"
version = "1.11.13"
authors = ["Sehyo Chang   sehyo@nginx.com"]

[lib]
doctest = false
test = true
crate-type = ["staticlib","rlib"]


[dependencies]
libc = "0.2.29"



[build-dependencies]
bindgen = "0.30.0"


